### ISSUE TITLE
Enhanced Host Details

### ISSUE THREAD

**Issue by sorantis** [elastic/infrastructure#20]
**Summary of the problem** 
Today Node details page provides only limited information about hosts/k8s pods/containers. While it's better than nothing, we have the possibility to surface a lot more to the users and improve overall user experience.

**User stories**
As as admin I want to be able to see enhanced details of my hosts, based on the information collected by Metricbeat so that I could get more insights about what's happening inside every host in my infrastructure.

**Details to expose**
<img width="1744" alt="node details" src="https://user-images.githubusercontent.com/1685068/87681996-9d2d7f00-c77f-11ea-93c6-ef0bb1882df0.png">

Product Brief: coming soon

**Comment by katrin-freihofner** [comment]
@sorantis does this also affect Kubernetes and AWS? And if so, could you provide more details on the difference?

**Comment by sorantis** [comment]
This is only for Hosts. Kubernetes will be covered separately. AWS will probably not be covered because we're moving to resource centric views as opposed to provider centric.

**Comment by fearful-symmetry** [comment]
Copying my thoughts over to here, since I've been chatting about this with a few folks. Figuring out the exact data shown by the system module is fairly important, since right now it's our best set of requirements for what system metrics the Agent should be sending OOTB. Right now those defaults are tied to the system dashboards, which doesn't really make sense in the context of x-pack and agent, particularly when you consider that a large part of the system dashboard is essentially a hacked-together emulation of the Metrics UI. If we can at least hammer out a definitive list of what exactly we need for the Host Details/Metrics UI going forward, it would help a lot with the direction of the System Integration on Agent.

**Comment by fearful-symmetry** [comment]
Something else: Going forward, we're going to need a certain amount of dynamic logic in the metrics UI. For example, `load` is a posix concept that we currently report on the top of the Host Detail UI. When we expand that to windows, it'll probably be an entirely different concept, and should be labeled and presented differently. Giving the front end knowledge of the OS it's reporting on, or even the ability to dynamically generate charts, will probably be something we'll want going forward.

**Comment by sorantis** [comment]
@fearful-symmetry agreed. I'm tracking the progress of [this component](https://github.com/elastic/kibana/issues/75650) that should enable ad-hoc access to host logs right from the host details ui.

**Comment by exekias** [comment]
This is looking awesome @hbharding @sorantis! I had a look to the designs and wanted to leave a few comments, please let me know if this is not the right place:

- For the properties tab, I think many of them can be actionable (maybe a tag-like look?). Clicking in one of the values would go back to the waffle view, filtering it to the hosts with that same property. Somehow this educates users on the power of search & filtering metadata.
- Rename `properties` to `System info` or just `Info`?
- Love the processes list! Would it be possible to so a sparkline instead of current value for CPU & Mem? I expect containers view to have a similar look
- Have you explored what will be shown for the case where system module is not running for that host? We know about it but we don't have much data. A basic view with what we have + a call to action to install the agent would be nice.

**Comment by sorantis** [comment]
@exekias thanks for the feedback!

**Comment by hbharding** [comment]
Thanks for the feedback @exekias!

> For the properties tab, I think many of them can be actionable (maybe a tag-like look?). Clicking in one of the values would go back to the waffle view, filtering it to the hosts with that same property. Somehow this educates users on the power of search & filtering metadata.

I like this idea a lot! I ended up doing something very similar to what can be found in the logs ui when you view the log details.

![image](https://user-images.githubusercontent.com/847805/95285536-0678d780-082f-11eb-90c9-c5d2c0c1db39.png)

> Rename properties to System info or just Info?

Naming is hard :) Is there a reason you prefer "info"? I don't have a strong opinion here. I think I saw the word "Properties" used somewhere when I was looking at other products. Internally, I think we sometimes refer to these as "node metadata".

> Love the processes list! Would it be possible to so a sparkline instead of current value for CPU & Mem? I expect containers view to have a similar look

Done! And we can do the same for the Container tab. I think I may need to add a note somewhere to indicate to the user the time range that the sparkline spans. 1 hour? 1 day? etc.

![image](https://user-images.githubusercontent.com/847805/95286026-31aff680-0830-11eb-93ff-206558bf2fe3.png)

> Have you explored what will be shown for the case where system module is not running for that host? We know about it but we don't have much data. A basic view with what we have + a call to action to install the agent would be nice.

Good point. I think something like this may work... though the language may need some tuning. I wrote this with Elastic Agent in mind, but it may need to be more generic to support Metricbeat usage. I think we could do something very similar on the Logs tab if the user doesn't have logs setup yet.

![image](https://user-images.githubusercontent.com/847805/95286279-e8ac7200-0830-11eb-8404-8b9b356348d6.png)

**Comment by hbharding** [comment]
![image](https://user-images.githubusercontent.com/847805/95285424-c1ed3c00-082e-11eb-831f-5b21fb96fabe.png)


I made a short [screencast](https://www.loom.com/share/6ee1dca1c7eb447cad54fb81372cf74f) that walks through my most recent designs based on previous discussions. You can also check out the [prototype](https://www.figma.com/proto/IOLwZBzAtazPG6ATEDDIcb/Enhanced-Node-Details?node-id=96%3A12883&viewport=3519%2C524%2C0.4645957946777344&scaling=contain) or [design file](https://www.figma.com/file/IOLwZBzAtazPG6ATEDDIcb/Enhanced-Node-Details?node-id=96%3A21488) in Figma.

**Comment by hbharding** [comment]
Small update: I removed the search bar from the "properties" tab to simplify and reduce scope. It feels unnecessary. I was originally concerned that there could be an over abundance of field/value pairs that would warrant the user having the ability to search for something specific, however after talking with @sorantis I don't think this will be the case.
